#ifndef MONITORING_CONTROLLER_CONSTANTS_H_
#define MONITORING_CONTROLLER_CONSTANTS_H_ 1

#define MONITORING_CONTROLLER_MODULE_NAME "MonitoringController"

#endif //MONITORING_CONTROLLER_CONSTANTS_H_

