#!/bin/bash

#Author: Sergio Nuccio
#Date: November 7th 2015
#Brief: stop script for a VNF type 5 implemented with openvswitch


#dependencies: openvswitch

#command line: 
#	sudo ./start $1 $2

#$1 LSI ID								(e.g. 2)
#$2 NF name								(e.g. OFbridge)

if (( $EUID != 0 )) 
then
    echo "[$0] This script must be executed with ROOT privileges"
    exit 0
fi

if [ $# -le 2 ]
then
	echo "[$0] This script needs at least 2 arguments"
	echo -e "\nUsage:\n$0 <LSI_ID> <NF_name>\n"
	exit 1
fi


#debug
set -x

#bridge name: <lsi_ID>_<NFname>_ofb
br_name=$1_$2_ofb

#db_name: <lsi_ID>_<NFname>.db
db_name=$1_$2.db

#kill ovsdb process???
echo "to be implemented!!!"
#remove ovs database
#rm /usr/local/etc/openvswitch/$db_name

#remove log files
#rm /var/log/openvswitch/ovs-vswitchd_$db_name.log
#rm /var/log/openvswitch/ovsdb-server_$db_name.log

#remove pid files
#rm /var/run/openvswitch/$db_name.pid
#rm /var/run/openvswitch/vswitchd$db_name.pid

#delete the ovs bridge
#ovs-vsctl del-br $br_name

echo "[nativeNF_OF_bridge_start] openflow_bridge stopped"

exit 0
