#!/bin/bash

#Author: Sergio Nuccio
#Date: November 7th 2015
#Brief: stop script for a native network function that creates a ovs bridge
#	that receives OpenFlow rules from a controller.

#dependencies: openvswitch

#$1 LSI ID								(e.g. 2)
#$2 NF name								(e.g. OFbridge)
#$3 number_of_ports							(e.g. 3)
#The next $4 parameters are the names of the ports of the NF		(e.g. vEth0 vEth1 vEth2)
#The first of them is connected to the controller

if (( $EUID != 0 )) 
then
    echo "[nativeNF_OF_bridge_stop] This script must be executed with ROOT privileges"
    exit 0
fi

#debug
#set -x

#bridge name: <lsi_ID>_<NFname>_ofb
br_name=$1_$2_ofb

#delete virtual links between this bridge and the LSI
#restore original status of the ports connected to the LSI
current=4
for (( c=1; c < $3; c++ ))
do
	
	#create peer port on this bridge (type patch)
	ovs-vsctl del-port $br_name ${!current}_p
	
	#change type of the port on the LSI
	ovs-vsctl set Interface ${!current} type=internal
	
	#remove option for virtual link on the port on the LSI
	ovs-vsctl remove Interface ${!current} options peer=${!current}_p

	current=`expr $current + 1`

done

#delete the ovs bridge
ovs-vsctl del-br $br_name

echo "[nativeNF_OF_bridge_start] openflow_bridge stopped"

exit 0


